# Choose whatever you want, version >= 1.16
FROM golang:1.20-alpine

WORKDIR /app
ENV CGO_ENABLED 1

RUN apk update --no-cache && apk add --no-cache tzdata gcc musl-dev

RUN go install github.com/cosmtrek/air@latest

COPY go.mod go.sum ./
RUN go mod download

CMD ["air"]
